gpu_id: 0
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expTGIF-QAFrameQA'

train:
  lr: 0.00005
  batch_size: 32
  restore: False
  max_epochs: 25
  word_dim: 300
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 3


val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'tgif-qa'
  question_type: 'frameqa'
  data_dir: '/media/lmy/processing/dataset/paper6/frameqa'
  save_dir: '/media/lmy/data1/lmy/result/paper6_fly'