gpu_id: 0
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expTGIF-QATransition'

train:
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 25
  word_dim: 300
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'tgif-qa'
  question_type: 'transition'
  data_dir: '/media/silence/8E9650559650403F/dateset/transition'
  save_dir: '/mnt/426240C46240BF03/code_qa/feature/results_e2e'